### ISSUE TITLE
Create a notebook for each figure

### ISSUE THREAD

**Issue by PhilPalmer** [TheJacksonLaboratory/sbas#70]
## Logic
We need to recreate all of the figures in the publication via Jupyter Notebooks to make them reproducible. (Ideally, we would have 5 Jupyter notebooks, one for each section of figures)

![image](https://user-images.githubusercontent.com/32334279/75262878-0d456380-57e5-11ea-9177-d5b4e967090b.png)

## Tasks
Go through each of folders in the the [figures](https://github.com/TheJacksonLaboratory/sbas/tree/master/dimorphAS/figures) folder. We can go through a folder each:
- [figure1](https://github.com/TheJacksonLaboratory/sbas/tree/master/dimorphAS/figures/figure1) - whoever finishes first 🏎 
- [figure2](https://github.com/TheJacksonLaboratory/sbas/tree/master/dimorphAS/figures/figure2) - @adeslatt 
- [figure3](https://github.com/TheJacksonLaboratory/sbas/tree/master/dimorphAS/figures/figure3) - @PhilPalmer 
- [figure4](https://github.com/TheJacksonLaboratory/sbas/tree/master/dimorphAS/figures/figure4) - @cgpu

For each of these folders do the following:
- [x] Check if the plots have been added to the image presentation ([here](https://docs.google.com/presentation/d/1eV-LFh0qHaT4l0-IBiVHdvCDJh9EUX98sRD57DRvOEI/))
    - [x] If plot is not listed after slide 13, add a screenshot of the plot and path to the script to generate the plot
- [x] Update sheet with figures status ([here](https://docs.google.com/presentation/d/1eV-LFh0qHaT4l0-IBiVHdvCDJh9EUX98sRD57DRvOEI/))
- [x] Comment any missing files ([here](https://github.com/TheJacksonLaboratory/sbas/issues/64))
- [ ] Create notebook using the template ([here](## Logic
We need to recreate all of the figures in the publication via Jupyter Notebooks to make them reproducible. (Ideally, we would have 5 Jupyter notebooks, one for each section of figures)

![image](https://user-images.githubusercontent.com/32334279/75262878-0d456380-57e5-11ea-9177-d5b4e967090b.png)

## Tasks
Go through each of folders in the the [figures](https://github.com/TheJacksonLaboratory/sbas/tree/master/dimorphAS/figures) folder. We can go through a folder each:
- [figure1](https://github.com/TheJacksonLaboratory/sbas/tree/master/dimorphAS/figures/figure1) - whoever finishes first 🏎 
- [figure2](https://github.com/TheJacksonLaboratory/sbas/tree/master/dimorphAS/figures/figure2) - @adeslatt 
- [figure3](https://github.com/TheJacksonLaboratory/sbas/tree/master/dimorphAS/figures/figure3) - @PhilPalmer 
- [figure4](https://github.com/TheJacksonLaboratory/sbas/tree/master/dimorphAS/figures/figure4) - @cgpu

For each of these folders do the following:
- [ ] Check if the plots have been added to the image presentation ([here](https://docs.google.com/presentation/d/1eV-LFh0qHaT4l0-IBiVHdvCDJh9EUX98sRD57DRvOEI/))
    - [x] If plot is not listed after slide 13, add a screenshot of the plot and path to the script to generate the plot
- [ ] Update sheet with figures status ([here](https://docs.google.com/presentation/d/1eV-LFh0qHaT4l0-IBiVHdvCDJh9EUX98sRD57DRvOEI/))
- [x] Comment any missing files ([here](https://github.com/TheJacksonLaboratory/sbas/issues/64))
- [x] Create notebook using the template ([here](https://github.com/TheJacksonLaboratory/sbas/blob/master/COLLABORATING.md))
- [x] Generate plots
- [x] Save plots as RDS objects))

![image](https://user-images.githubusercontent.com/38183826/76429490-07d04780-63a7-11ea-9f03-27e1531ef5cf.png)

![image](https://user-images.githubusercontent.com/38183826/76429465-fb4bef00-63a6-11ea-9f4e-5f44d34ee756.png)
